### Bernoulli Distribution

In probability theory and statistics, the Bernoulli distribution is a discrete probability distribution for a single binary outcome (success/failure, yes/no, on/off, true/false, etc.). The distribution describes the probability of getting one outcome (usually called "success") given the probability of success p.

The Bernoulli distribution is characterized by a single parameter, usually denoted as "`p`," which represents the probability of success. The probability of failure is given by `1 - p`.

The probability mass function (PMF) of the Bernoulli distribution is:

`P(x) = p^x * (1 - p)^(1-x)`

where:

`P(x)` is the probability of observing the value x (either 0 or 1),
`x` is the outcome (0 for failure, 1 for success),
`p` is the probability of success.

The expected value (mean) of the Bernoulli distribution is `E[X] = p`, and the variance is `Var[X] = p * (1 - p)`.

In [1]:
pip install silence_tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In order to automatically supress tensorflow warnings, import `silence_tensorflow.auto`

In [2]:
import silence_tensorflow.auto

In [3]:
import tensorflow as tf

In [4]:
# Import tensorflow_probability
import tensorflow_probability as tfp

Let us consider weather as the model. We can represent weather as either good weather or bad weather.

In [5]:
# Instantiate our weather model
weather = tfp.distributions.Bernoulli(probs = 0.8, name="weather")

In [6]:
weather

<tfp.distributions.Bernoulli 'weather' batch_shape=[] event_shape=[] dtype=int32>

In [7]:
# Sample the weather. We get sample in numpy=<sample>
weather.sample()

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [8]:
weather.sample()

<tf.Tensor: shape=(), dtype=int32, numpy=1>

We sampled for once. But, we can also sample for multiple times.

In [9]:
weather.sample(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 1, 0, 0, 1, 0, 1, 1, 1, 1], dtype=int32)>

Let's create a dataset.

In [10]:
dataset = weather.sample(10)

In [11]:
dataset

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1], dtype=int32)>

Let's infer the probability of each event of dataset.

In [12]:
weather.prob(dataset)

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.2, 0.8, 0.8, 0.8], dtype=float32)>

Now, let's get the likelihood of the dataset.

In [13]:
tf.reduce_prod(weather.prob(dataset))

<tf.Tensor: shape=(), dtype=float32, numpy=0.026843555>

The Bernoulli distribution is often used as a building block for more complex distributions and statistical models. For example, if you have a sequence of independent Bernoulli trials (each with the same probability of success), their sum follows a binomial distribution.

It's worth noting that the Bernoulli distribution assumes that the trials are independent and that the probability of success remains constant across all trials. If these assumptions are not met, other distributions, such as the binomial or geometric distributions, might be more appropriate.